class KeypadOperator
  def presses: (String targets) -> Integer
  
  class Robot < KeypadOperator
    type keypad = Hash[String, Complex]
    DPAD: keypad
    
    @arm: Complex
    @presses: Hash[String, Integer]
    def initialize: (keypad keypad, KeypadOperator operator) -> void
    def presses: ...
    
    ROUTE_RUDL: Hash[String, Integer]
    ROUTE_LDUR: Hash[String, Integer]
  end
end
