class KeypadOperator
  def presses: (String targets) -> Integer
  
  class Robot < KeypadOperator
    type keypad = Hash[String, Complex]
    def keypad: () -> keypad
    
    @arm: Complex
    @presses: Hash[String, Integer]
    def initialize: (KeypadOperator operator) -> void
    def presses: ...
    
    ROUTE_RUDL: Hash[String, Integer]
    ROUTE_LDUR: Hash[String, Integer]
    def route_key: (Complex target_coords) -> Hash[String, Integer]
    def route_to: (String target) -> String
    
    NUMPAD: keypad
    class DPad < Robot
      KEYPAD: keypad
      def keypad: ...
    end
  end
end
