class Region
  GARDEN: Array[Array[String?|Region]]
  
  attr_accessor perimeter: Integer
  attr_reader side_next_points: Array[Set[[Integer, Integer]]]
  @sides: Integer?
  def sides: () -> Integer
  
  def self.neighbors: (Integer x, Integer y) -> Array[[Integer, Integer]]
  def self.flood_fill: (String plant, Integer x, Integer y, ?Region? region) -> void
end
